#:schema ./schema.json

id = "focalboard"
name = "Focalboard"
icon = "https://avatars.githubusercontent.com/u/9828093?s=48&v=4"
description = "Focalboard is an open source, multilingual, self-hosted project management tool that's an alternative to Trello, Notion, and Asana."

[source]
image = "mattermost/focalboard:latest"

[[ports]]
id = "web"
port = 8000
type = "HTTP"
