#:schema ./schema.json

id = "postgresql"
name = "PostgreSQL"
description = "PostgreSQL is a powerful, open source object-relational database system."
icon = "https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg"

[source]
image = "postgres:12.2"

[[ports]]
id = "database"
port = 5432
type = "TCP"

[[volumes]]
id = "data"
dir = "/var/lib/postgresql/data"

[env]
POSTGRES_PASSWORD = { default = "${PASSWORD}", expose = true }
POSTGRES_USER = { default = "root" }
PGDATA = { default = "/var/lib/postgresql/data/pgdata" }

POSTGRES_HOST = { default = "${CONTAINER_HOSTNAME}", expose = true, readonly = true }
POSTGRES_PORT = { default = "${DATABASE_PORT}", expose = true, readonly = true }

POSTGRES_USERNAME = { default = "${POSTGRES_USER}", expose = true, readonly = true }

POSTGRES_CONNECTION_STRING = { default = "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/db", expose = true, readonly = true }
POSTGRES_CONNECTION_STRING_PORTFORWARDED = { default = "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${DB_PORT_FORWARDED_HOSTNAME}:${DB_PORT_FORWARDED_PORT}/db", readonly = true }

[[instructions]]
type = "TEXT"
title = "Command to connect to your PostgreSQL"
content = "psql ${POSTGRES_CONNECTION_STRING_PORTFORWARDED}"
showWhen = "PORT_FORWARDING"

[[instructions]]
type = "PASSWORD"
title = "PostgreSQL Connection String (in project)"
content = "${POSTGRES_CONNECTION_STRING}"
category = "Connection Strings"

[[instructions]]
type = "PASSWORD"
title = "PostgreSQL Connection String (port forwarded)"
content = "${POSTGRES_CONNECTION_STRING_PORTFORWARDED}"
showWhen = "PORT_FORWARDING"
category = "Connection Strings"

[[instructions]]
type = "TEXT"
title = "PostgreSQL username"
content = "${POSTGRES_USERNAME}"
category = "Credentials"

[[instructions]]
type = "PASSWORD"
title = "PostgresSQL password"
content = "${POSTGRES_PASSWORD}"
category = "Credentials"

[[instructions]]
type = "TEXT"
title = "PostgreSQL host (in project)"
content = "${POSTGRES_HOST}"
category = "Hostname & Port"

[[instructions]]
type = "TEXT"
title = "PostgreSQL host (port forwarded)"
content = "${PORT_FORWARDED_HOSTNAME}"
showWhen = "PORT_FORWARDING"
category = "Hostname & Port"

[[instructions]]
type = "TEXT"
title = "PostgreSQL port (in project)"
content = "${POSTGRES_PORT}"
category = "Hostname & Port"

[[instructions]]
type = "TEXT"
title = "PostgreSQL port (port forwarded)"
content = "${DATABASE_PORT_FORWARDED_PORT}"
category = "Hostname & Port"
